### ISSUE TITLE
Will we get any resources for frontend as well?

### ISSUE THREAD

**Issue by Bishwas-py** [Mostafa-DE/jwt-auth-django-NextJs#1]
I am doing Next Js authentication with Django Rest Framework Simple JWT token, can you help me how it can be done?

**Comment by Mostafa-DE** [comment]
Hi @Bishwas-py  i don't know why front-end file doesn't open i will check it again soon.

**Comment by Mostafa-DE** [comment]
@Bishwas-py Please see this repo, if it is useful 
https://github.com/Mostafa-DE/simple-auth-django-react
